//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamEVotingWebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CandidateSet
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateSet()
        {
            this.UserSet = new HashSet<UserSet>();
        }
    
        [Required]
        public int Candidate_Id { get; set; }
        [Required]
        public string Candidate_FirstName { get; set; }
        [Required]
        public int Candidate_Age { get; set; }
        [Required]
        public int Region_Id { get; set; }
        [Required]
        public int Faction_Id { get; set; }
        [Required]
        public Nullable<int> NumberOfVotes { get; set; }
        [Required]
        public string Candidate_LastName { get; set; }

        public string Fullname
        {
            get
            {
                return string.Format("{0} {1}", Candidate_FirstName, Candidate_LastName);
            }
        }
        public virtual RegionSet RegionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSet> UserSet { get; set; }
        public virtual FactionSet FactionSet { get; set; }
        public List<RegionSet> regions { get; internal set; }
        public List<FactionSet> factions { get; internal set; }
    }
}
