//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamEVotingWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateSet()
        {
            this.UserSet = new HashSet<UserSet>();
        }
    
        public int Candidate_Id { get; set; }
        public string Candidate_FirstName { get; set; }
        public int Candidate_Age { get; set; }
        public int Region_Id { get; set; }
        public int Faction_Id { get; set; }
        public Nullable<int> NumberOfVotes { get; set; }
        public string Candidate_LastName { get; set; }
    
        public virtual RegionSet RegionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSet> UserSet { get; set; }
        public virtual FactionSet FactionSet { get; set; }
        public List<RegionSet> regions { get; set; }
        public List<FactionSet> factions { get; set; }
    }
}
