//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamEVotingWebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FactionSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactionSet()
        {
            this.CandidateSet = new HashSet<CandidateSet>();
            this.RegionSet = new HashSet<RegionSet>();
        }
        [Required]
        public int Faction_Id { get; set; }
        [Required]
        public string Faction_Name { get; set; }
        [Required]
        public int NumberOfMembers { get; set; }
        public string Faction_ImageLogo { get; set; }
        public string Faction_ImageLogoTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateSet> CandidateSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionSet> RegionSet { get; set; }
    }
}
