//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamEVotingWebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamEVotingDBEntities : DbContext
    {
        public TeamEVotingDBEntities()
            : base("name=TeamEVotingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidateSet> CandidateSet { get; set; }
        public virtual DbSet<FactionSet> FactionSet { get; set; }
        public virtual DbSet<RegionSet> RegionSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
    }
}
