//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamEVotingWebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSet()
        {
            this.VisitorInfo = new HashSet<VisitorInfo>();
        }

        [Required]
        public int User_Id { get; set; }
        [Required]
        public string User_FirstName { get; set; }
        [Required]
        public string User_LastName { get; set; }
        [Required]
        public int Candidate_Id { get; set; }
        public string User_Email { get; set; }
    
        public virtual CandidateSet CandidateSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorInfo> VisitorInfo { get; set; }
        public List<CandidateSet> candidates { get; set; }
    }
}
