//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamEVotingWebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VisitorInfo
    {
        [Required]
        public int Visitor_Id { get; set; }
        [Required]
        public string VisitorLandingPage { get; set; }
        [Required]
        public string VisitorBrowser { get; set; }
        [Required]
        public string VisitorIP { get; set; }
        public Nullable<System.DateTime> Visited_DateTime { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual UserSet UserSet { get; set; }
    }
}
